### ISSUE TITLE
Unable to parse the package

### ISSUE THREAD

**Issue by mhm199** [reisxd/revanced-builder#21]
so after using the revanced builder thing the part where is says "Installing MicroG" and then the command prompt just closes, I was expecting something like more guidelines but it just closes, I don't know if that's normal and then I checked the folder named "revanced-cache" and I see revanced_raw.apk in the folder and then I tried moving the file in my phone and then manually install it on my phone but it can't because it says "Unable to parse the package". By the way I used this with adb and my phone connected to my laptop. Right now I'm trying to debug and see what is wrong or maybe I am just missing something. Thanks and don't worry I have a lot of patience for someone to reply.

**Comment by mhm199** [comment]
Update: tried installing the "revanced_raw.apk" through adb and this error showed up. I don't know if this will help anything but ok.
![image](https://user-images.githubusercontent.com/57556087/177075852-78e37c58-9d55-4420-bb5b-53ced8e59bb1.png)

**Comment by reisxd** [comment]
Hey, try running revanced-builder inside CMD, there might be an issue you are encountering and because MicroG gets installed, it closes. I have to add something there to pause the app.

**Comment by reisxd** [comment]
Hey, try running revanced-builder inside CMD, there might be an issue you are encountering and because MicroG gets installed, it closes. I have to add something there to pause the app.

**Comment by reisxd** [comment]
Can you also try deleting revanced-cache? For some people and for some reason, revanced-cli deleted that folder automatically and not build anything.

**Comment by reisxd** [comment]
Fixed in v1.2.3.

**Comment by mhm199** [comment]
Hi, so sorry to bother but the issue persists for me. The cmd still closes on "Installing MicroG" part and I tried running it inside cmd and deleting the revanced-cache folder but the issue persists. tried updating my Java to latest version but the issue still persists. Could be hopless right now. anyways still figuring out why is this happening.

**Comment by reisxd** [comment]
Can you send the console output?

**Comment by mhm199** [comment]
Here
![image](https://user-images.githubusercontent.com/57556087/177103887-9385752b-7528-4e98-b0b8-85970769d20d.png)

**Comment by mhm199** [comment]
it successfully installs microg in my phone but the "revanced-aligned.apk" and "revanced-raw.apk" are unable to install because of "unable to parse package" ye

**Comment by mhm199** [comment]
could be my phone is the problem

**Comment by reisxd** [comment]
> it successfully installs microg in my phone but the "revanced-aligned.apk" and "revanced-raw.apk" are unable to install because of "unable to parse package" ye

You didn't exclude any patches and still, for some reason, you didn't have the version selector. It's supposed to not show when you are excluding microg-support, but you never did exclude it.

Also, no. It's not a phone issue. Those apks are not meant to be installed.

**Comment by reisxd** [comment]
@mhm199 Can you try to build ReVanced with `java -jar revanced/revanced-cli-2.3.0-all.jar -b revanced-patches-2.7.0.jar -m revanced/app-release-unsigned.apk -a revanced/youtube.apk -o revanced.apk`

**Comment by mhm199** [comment]
Here is my java version
![image](https://user-images.githubusercontent.com/57556087/177106790-51034d67-c840-47eb-96d4-8f64b8169ca2.png)

**Comment by mhm199** [comment]
and where do I run this? `java -jar revanced/revanced-cli-2.3.0-all.jar -b revanced-patches-2.7.0.jar -m revanced/app-release-unsigned.apk -a revanced/youtube.apk -o revanced.apk`

**Comment by reisxd** [comment]
> Here is my java version ![image](https://user-images.githubusercontent.com/57556087/177106790-51034d67-c840-47eb-96d4-8f64b8169ca2.png)

Theres the problem. You don't run Zulu JDK. Please get it from [here.](https://www.azul.com/downloads/?version=java-17-lts&package=jdk)

**Comment by mhm199** [comment]
> > Here is my java version ![image](https://user-images.githubusercontent.com/57556087/177106790-51034d67-c840-47eb-96d4-8f64b8169ca2.png)
> 
> Theres the problem. You don't run Zulu JDK. Please get it from [here.](https://www.azul.com/downloads/?version=java-17-lts&package=jdk)

omg thx so much like actually. 👍

**Comment by ShreeyansB** [comment]
Im having the same problem. 
![image](https://user-images.githubusercontent.com/37953798/177164959-9ec2debb-c823-44b7-9e70-55a64616aa59.png)
![image](https://user-images.githubusercontent.com/37953798/177165192-cf94e1ff-b95d-42f7-8efa-ea4d6211b82f.png)
![image](https://user-images.githubusercontent.com/37953798/177164877-07b05d9f-aaf2-4cae-b693-8349ace3a91a.png)

Only microG gets installed. Youtube doesnt

**Comment by ShreeyansB** [comment]
Its not.
![image](https://user-images.githubusercontent.com/37953798/177167370-c30239df-ebf9-43a5-a408-4caec9f56774.png)
